### ISSUE TITLE
Compatibility with DepthEye 3D Visual TOF Depth Camera

### ISSUE THREAD

**Issue by PabloFreitasUfsc** [SICKAG/sick_visionary_t#21]
Do you think that is possible do use this driver to a camera that is in the link below
https://www.seeedstudio.com/DepthEye-3D-visual-TOF-Depth-Camera-p-3025.html

If not, do you know any driver from ROS that works on that camera?

**Comment by richean** [comment]
Hello Pablo,
the driver is very specific to the [Visionary-T](https://www.sick.com/de/en/vision/3d-vision/visionary-t/v3s100-2aabaab/p/p551864?ff_data=JmZmX2lkPXA1NTE4NjQmZmZfbWFzdGVySWQ9cDU1MTg2NCZmZl90aXRsZT1WM1MxMDAtMkFBQkFBQiZmZl9xdWVyeT0mZmZfcG9zPTMmZmZfb3JpZ1Bvcz0zJmZmX3BhZ2U9MSZmZl9wYWdlU2l6ZT04JmZmX29yaWdQYWdlU2l6ZT04JmZmX3NpbWk9OTEuMA==) camera. The driver converts the image data received from the Visionary-T via network to the ROS data format.
So there have to be a own driver for each data format on the market. As long the mentioned camera does not share the data format with an other camera, you need to write an extra driver for this one.
/Andreas Richert
